execution:
    type: batch
    current-catalog: default_catalog
    current-database: default_database

s3:
    access-key: minioadmin
    secret-key: minioadmin
    path-style-access: true
    endpoint: http://minio:9000

fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
fs.s3.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
